#!/usr/bin/env bash
# A new Nginx server configured so that /redirect_me is redirecting to another page

# Packake update and nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Create index page
echo "Hello World" | sudo tee /var/www/html/index

# Redirect error 303
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/ permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

#Test Nginx configuration file
sudo nginx -t
