#!/usr/bin/env bash

# My SSH configuration file for the local SSH client
# My SSH client configuration must be configured to use the private
# key ~/.ssh/school
# My SSH client configuration must be configured to refuse to authenticate
# using a password

Host 100.26.249.28
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
